### ISSUE TITLE
I'm only getting the first letter from hanzi

### ISSUE THREAD

**Issue by webmagnets** [pepebecker/pinyin-convert#2]
When I use this code:

```convert('我').then(function(result){console.log(result)}).catch(function(e){console.error})```
I am getting this output: ```w```

I would expect to get ```wo3```.

**Comment by fultonm** [comment]
我也有这个问题
![image](https://user-images.githubusercontent.com/13190319/35706652-71a90c00-075b-11e8-84e1-0eb2ea4f65c9.png)

**Comment by pepebecker** [comment]
This problem should be resolved in the latest update.
@webmagnets  & @fultonm can you guys confirm if it's working?
